apiVersion: "v1"
kind: "Service"
metadata:
  name: "todo-service"
  namespace: "default"
  labels:
    app: todo
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 4200
  selector:
    app: "todo"
  type: "LoadBalancer"
  loadBalancerIP: ""
